In [14]:
import numpy as np

In [15]:
a = np.arange(1,26,1)

In [16]:
newArray = a.reshape(5,5)
newArray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [17]:
newArray[[0,1,2,4]]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]])

In [18]:
newArray[:,[1,2,3]]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [ ]:
randArray = np.random.randint(1,100, 24).reshape(4, 6)
great_20 = randArray[randArray >20]

array([62, 92, 34, 75, 99, 68, 89, 68, 92, 32, 23, 69, 55, 82, 49, 29, 98,
       71, 38, 37])

In [23]:
evenMask = randArray % 2 == 0
evenArr = randArray[evenMask]
evenArr

array([62,  8, 92, 34, 68, 68, 92, 32, 82, 98, 38, 20])

In [27]:
mulMask = (randArray > 50) & (randArray % 2 == 0)
randArray[mulMask]

array([62, 92, 68, 68, 92, 82, 98])

In [30]:
arr1 = np.arange(1,13).reshape(4,3)
arr1.ndim

2

In [31]:
arr2 = np.arange(3)
arr2.ndim

1

In [34]:
arr3 = np.arange(16).reshape(4,4)
arr4 = np.arange(4).reshape(2,2)
print(arr3)
print(arr4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1]
 [2 3]]


In [35]:
print(arr3 + arr4)

ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 